[I 16:46:42.710 NotebookApp] Serving notebooks from local directory: /root/notebook/meus-arquivos
[I 16:46:42.710 NotebookApp] Jupyter Notebook 6.4.5 is running at:
[I 16:46:42.710 NotebookApp] http://localhost:8970/?token=29a08277c2bd0343031307e954a4744e6c5b88ccd3587b5d
[I 16:46:42.710 NotebookApp]  or http://127.0.0.1:8970/?token=29a08277c2bd0343031307e954a4744e6c5b88ccd3587b5d
[I 16:46:42.710 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:46:42.718 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/nbserver-1251-open.html
    Or copy and paste one of these URLs:
        http://localhost:8970/?token=29a08277c2bd0343031307e954a4744e6c5b88ccd3587b5d
     or http://127.0.0.1:8970/?token=29a08277c2bd0343031307e954a4744e6c5b88ccd3587b5d
[I 16:47:16.352 NotebookApp] 302 GET / (127.0.0.1) 1.140000ms
[I 07:27:24.456 NotebookApp] 302 GET / (127.0.0.1) 576.060000ms
[I 07:27:24.766 NotebookApp] 302 GET /tree? (127.0.0.1) 172.330000ms
[W 07:27:51.067 NotebookApp] 401 POST /login?next=%2Ftree%3F (127.0.0.1) 14.940000ms referer=http://localhost:8888/login?next=%2Ftree%3F
[W 07:28:20.593 NotebookApp] 401 POST /login?next=%2Ftree%3F (127.0.0.1) 2.420000ms referer=http://localhost:8888/login?next=%2Ftree%3F
[W 07:30:43.877 NotebookApp] 401 POST /login?next=%2Ftree%3F (127.0.0.1) 24.980000ms referer=http://localhost:8888/login?next=%2Ftree%3F
[W 07:32:47.246 NotebookApp] 401 POST /login?next=%2Ftree%3F (127.0.0.1) 7.320000ms referer=http://localhost:8888/login?next=%2Ftree%3F
[W 07:33:53.759 NotebookApp] 401 POST /login?next=%2Ftree%3F (127.0.0.1) 2.300000ms referer=http://localhost:8888/login?next=%2Ftree%3F
[I 07:35:02.925 NotebookApp] 302 POST /login?next=%2Ftree%3F (127.0.0.1) 147.610000ms
[W 07:37:13.514 NotebookApp] Notebook Validador/Untitled.ipynb is not trusted
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7f4e18450400>(<Future finis...3d5"\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7f4e18450400>(<Future finis...3d5"\r\n\r\n'>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-57' coro=<HTTP1ServerConnection._server_request_loop() running at /usr/local/lib/python3.8/dist-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /kernel...73d5"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /usr/local/lib/python3.8/dist-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /usr/local/lib/python3.8/dist-packages/jupyter_client/manager.py:337>> is being executed.
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7f4e16551ee0>(<Future finis...3d5"\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7f4e16551ee0>(<Future finis...3d5"\r\n\r\n'>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-65' coro=<HTTP1ServerConnection._server_request_loop() running at /usr/local/lib/python3.8/dist-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /api/co...73d5"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /usr/local/lib/python3.8/dist-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /usr/local/lib/python3.8/dist-packages/jupyter_client/manager.py:337>> is being executed.
[I 07:37:14.079 NotebookApp] Kernel started: 2defaa68-de94-45b0-a44c-82313bd1db93, name: python3
[I 07:37:21.347 NotebookApp] Creating new notebook in /Validador
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7f4e183c2ee0>(<Future finis...3d5"\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7f4e183c2ee0>(<Future finis...3d5"\r\n\r\n'>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-67' coro=<HTTP1ServerConnection._server_request_loop() running at /usr/local/lib/python3.8/dist-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /api/co...73d5"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /usr/local/lib/python3.8/dist-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-43' coro=<MappingKernelManager.start_kernel() running at /usr/local/lib/python3.8/dist-packages/notebook/services/kernels/kernelmanager.py:176> cb=[IOLoop.add_future.<locals>.<lambda>() at /usr/local/lib/python3.8/dist-packages/tornado/ioloop.py:695]> is being executed.
[I 07:37:23.242 NotebookApp] Kernel started: 385df0ca-33ec-4f56-be41-e7a792240d61, name: python3
[I 07:39:23.850 NotebookApp] Saving file at /Validador/Resquest2Dataframe.ipynb
[I 07:41:26.357 NotebookApp] Starting buffering for 385df0ca-33ec-4f56-be41-e7a792240d61:0bec6a9465ac46b39ee4f2ecc71d62d0
[I 07:41:27.231 NotebookApp] Kernel restarted: 385df0ca-33ec-4f56-be41-e7a792240d61
[I 07:41:27.514 NotebookApp] Restoring connection for 385df0ca-33ec-4f56-be41-e7a792240d61:0bec6a9465ac46b39ee4f2ecc71d62d0
[I 07:41:29.869 NotebookApp] Replaying 3 buffered messages
[I 07:43:23.288 NotebookApp] Saving file at /Validador/Resquest2Dataframe.ipynb
[W 07:44:54.401 NotebookApp] Notebook Validador/versao01.ipynb is not trusted
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7f4e18442a00>(<Future finis...3d5"\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7f4e18442a00>(<Future finis...3d5"\r\n\r\n'>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-64' coro=<HTTP1ServerConnection._server_request_loop() running at /usr/local/lib/python3.8/dist-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /api/co...73d5"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /usr/local/lib/python3.8/dist-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-460' coro=<KernelManager._async_start_kernel() running at /usr/local/lib/python3.8/dist-packages/jupyter_client/manager.py:337>> is being executed.
[I 07:44:54.684 NotebookApp] Kernel started: c39940f8-0f91-41ad-9392-fd3ce3d0905a, name: python3
[I 07:45:23.263 NotebookApp] Saving file at /Validador/Resquest2Dataframe.ipynb
[I 07:47:23.801 NotebookApp] Saving file at /Validador/Resquest2Dataframe.ipynb
[I 07:47:55.096 NotebookApp] Starting buffering for 2defaa68-de94-45b0-a44c-82313bd1db93:78f31b1be43d4e59896e5453de9144e1
[I 07:48:19.431 NotebookApp] Starting buffering for c39940f8-0f91-41ad-9392-fd3ce3d0905a:aeaa846095aa4038837294227c8b2c85
[I 07:48:57.687 NotebookApp] Starting buffering for 385df0ca-33ec-4f56-be41-e7a792240d61:0bec6a9465ac46b39ee4f2ecc71d62d0
[I 11:28:59.531 NotebookApp] 302 GET / (127.0.0.1) 198.920000ms
[W 11:29:11.671 NotebookApp] Notebook Validador/Resquest2Dataframe.ipynb is not trusted
[I 11:57:12.190 NotebookApp] Saving file at /Validador/Resquest2Dataframe.ipynb
[I 11:59:06.576 NotebookApp] Starting buffering for 385df0ca-33ec-4f56-be41-e7a792240d61:0ad76452bd1b42ac9bc5038ed77a4607
[I 19:47:29.628 NotebookApp] 302 GET / (127.0.0.1) 127.450000ms
[I 19:47:38.166 NotebookApp] Creating new directory in 
[W 19:48:35.376 NotebookApp] delete /Untitled Folder
[I 19:48:44.759 NotebookApp] Creating new directory in 
[I 19:49:22.268 NotebookApp] Creating new notebook in /Untitled Folder
[I 19:49:26.450 NotebookApp] Kernel started: f3e6d9ae-d101-497e-8572-357400347411, name: python3
[I 19:51:26.168 NotebookApp] Saving file at /Untitled Folder/Resultado Futuro - ABEV3.ipynb
[I 19:53:27.121 NotebookApp] Saving file at /Untitled Folder/Resultado Futuro - ABEV3.ipynb
[I 19:54:13.740 NotebookApp] Saving file at /Untitled Folder/Resultado Futuro - ABEV3.ipynb
[I 19:54:28.283 NotebookApp] New terminal with automatic name: 1
ERROR:terminado.websocket:not able to serialize: expected string or bytes-like object
[I 19:55:26.133 NotebookApp] Saving file at /Untitled Folder/Resultado Futuro - ABEV3.ipynb
[I 19:57:26.114 NotebookApp] Saving file at /Untitled Folder/Resultado Futuro - ABEV3.ipynb
[I 19:59:26.084 NotebookApp] Saving file at /Untitled Folder/Resultado Futuro - ABEV3.ipynb
[I 20:01:26.171 NotebookApp] Saving file at /Untitled Folder/Resultado Futuro - ABEV3.ipynb
[I 20:02:24.249 NotebookApp] EOF on FD 72; stopping reading
[I 20:02:24.360 NotebookApp] Terminal 1 closed
[I 20:03:26.217 NotebookApp] Saving file at /Untitled Folder/Resultado Futuro - ABEV3.ipynb
[I 20:05:27.075 NotebookApp] Saving file at /Untitled Folder/Resultado Futuro - ABEV3.ipynb
[I 20:13:54.627 NotebookApp] Saving file at /Untitled Folder/Resultado Futuro - ABEV3.ipynb
[I 20:13:58.313 NotebookApp] Starting buffering for f3e6d9ae-d101-497e-8572-357400347411:d1726c7e73ee4633b73a8c325517c0bc
[I 20:14:00.952 NotebookApp] Saving file at /Validador/Resquest2Dataframe.ipynb
[I 20:14:02.814 NotebookApp] Starting buffering for 385df0ca-33ec-4f56-be41-e7a792240d61:3f0d8afe39f640c8854adb9ed6cbda97
[I 12:25:15.320 NotebookApp] 302 GET / (127.0.0.1) 129.220000ms
[W 12:25:24.692 NotebookApp] Notebook ResultadoFuturo/Resultado Futuro - ABEV3.ipynb is not trusted
[I 12:25:25.444 NotebookApp] Kernel started: 19005701-50eb-4eb9-8a67-a0496a5ebcf6, name: python3
[I 12:27:25.183 NotebookApp] Saving file at /ResultadoFuturo/Resultado Futuro - ABEV3.ipynb
[W 12:27:25.212 NotebookApp] Notebook ResultadoFuturo/Resultado Futuro - ABEV3.ipynb is not trusted
[I 12:35:24.974 NotebookApp] Saving file at /ResultadoFuturo/Resultado Futuro - ABEV3.ipynb
[W 12:35:24.980 NotebookApp] Notebook ResultadoFuturo/Resultado Futuro - ABEV3.ipynb is not trusted
[I 12:37:24.986 NotebookApp] Saving file at /ResultadoFuturo/Resultado Futuro - ABEV3.ipynb
[W 12:37:24.989 NotebookApp] Notebook ResultadoFuturo/Resultado Futuro - ABEV3.ipynb is not trusted
[I 12:39:24.975 NotebookApp] Saving file at /ResultadoFuturo/Resultado Futuro - ABEV3.ipynb
[W 12:39:24.981 NotebookApp] Notebook ResultadoFuturo/Resultado Futuro - ABEV3.ipynb is not trusted
[I 12:41:25.027 NotebookApp] Saving file at /ResultadoFuturo/Resultado Futuro - ABEV3.ipynb
[W 12:41:25.028 NotebookApp] Notebook ResultadoFuturo/Resultado Futuro - ABEV3.ipynb is not trusted
[I 12:43:24.974 NotebookApp] Saving file at /ResultadoFuturo/Resultado Futuro - ABEV3.ipynb
[W 12:43:24.974 NotebookApp] Notebook ResultadoFuturo/Resultado Futuro - ABEV3.ipynb is not trusted
[I 12:45:06.509 NotebookApp] Saving file at /ResultadoFuturo/Resultado Futuro - ABEV3.ipynb
[W 12:45:06.510 NotebookApp] Notebook ResultadoFuturo/Resultado Futuro - ABEV3.ipynb is not trusted
[I 12:47:25.207 NotebookApp] Saving file at /ResultadoFuturo/Resultado Futuro - ABEV3.ipynb
[I 14:18:27.918 NotebookApp] Starting buffering for 19005701-50eb-4eb9-8a67-a0496a5ebcf6:d2243173d9e843c780c2667157e13731
[I 12:45:56.434 NotebookApp] 302 GET / (127.0.0.1) 315.030000ms
[I 12:48:17.563 NotebookApp] Creating new notebook in /ResultadoFuturo
[I 12:48:20.169 NotebookApp] Kernel started: 6aeeb1ad-d8f5-41cc-ba97-61a7c9b35578, name: python3
[I 12:50:21.011 NotebookApp] Saving file at /ResultadoFuturo/Untitled.ipynb
[I 12:52:20.974 NotebookApp] Saving file at /ResultadoFuturo/Untitled.ipynb
[I 14:02:19.469 NotebookApp] Saving file at /ResultadoFuturo/Untitled.ipynb
[I 15:43:54.992 NotebookApp] Kernel interrupted: 6aeeb1ad-d8f5-41cc-ba97-61a7c9b35578
[I 15:44:18.548 NotebookApp] Saving file at /ResultadoFuturo/Untitled.ipynb
[I 15:44:57.502 NotebookApp] Starting buffering for 6aeeb1ad-d8f5-41cc-ba97-61a7c9b35578:5ab4f2de10aa4c078942f7a34e84f468
[I 15:44:59.819 NotebookApp] Kernel restarted: 6aeeb1ad-d8f5-41cc-ba97-61a7c9b35578
[I 15:44:59.932 NotebookApp] Restoring connection for 6aeeb1ad-d8f5-41cc-ba97-61a7c9b35578:5ab4f2de10aa4c078942f7a34e84f468
[I 15:45:03.726 NotebookApp] Replaying 6 buffered messages
[I 15:46:19.437 NotebookApp] Saving file at /ResultadoFuturo/Untitled.ipynb
[I 15:48:08.464 NotebookApp] Saving file at /ResultadoFuturo/Resultado Futuro - ABEV3.ipynb
[I 15:50:07.949 NotebookApp] Saving file at /ResultadoFuturo/Resultado Futuro - ABEV3.ipynb
[I 15:54:08.665 NotebookApp] Saving file at /ResultadoFuturo/Resultado Futuro - ABEV3.ipynb
[I 16:02:18.380 NotebookApp] Saving file at /ResultadoFuturo/Untitled.ipynb
[I 16:04:18.345 NotebookApp] Saving file at /ResultadoFuturo/Untitled.ipynb
[I 16:06:18.395 NotebookApp] Saving file at /ResultadoFuturo/Untitled.ipynb
[I 16:08:13.393 NotebookApp] Saving file at /ResultadoFuturo/Untitled.ipynb
[I 16:10:19.273 NotebookApp] Saving file at /ResultadoFuturo/Untitled.ipynb
[I 16:18:19.239 NotebookApp] Saving file at /ResultadoFuturo/Pesquisando ABEV3-2.ipynb
[I 16:27:19.497 NotebookApp] Starting buffering for 19005701-50eb-4eb9-8a67-a0496a5ebcf6:c92486b2ff7e48e280bfa4342f615fd4
[I 16:27:20.841 NotebookApp] Starting buffering for 6aeeb1ad-d8f5-41cc-ba97-61a7c9b35578:5ab4f2de10aa4c078942f7a34e84f468
[I 10:42:02.925 NotebookApp] 302 GET / (127.0.0.1) 216.420000ms
[W 10:43:07.296 NotebookApp] Notebook Validador/versao01.ipynb is not trusted
[I 10:43:20.929 NotebookApp] Starting buffering for c39940f8-0f91-41ad-9392-fd3ce3d0905a:569d109187e945728bd31c493e4f6a39
[I 10:43:25.661 NotebookApp] Saving file at /Validador/Resquest2Dataframe.ipynb
[W 10:43:30.009 NotebookApp] Notebook Validador/Untitled.ipynb is not trusted
[W 10:43:42.136 NotebookApp] delete /Validador/versao01.ipynb
[W 10:43:42.271 NotebookApp] delete /Validador/Untitled.ipynb
[I 10:43:42.276 NotebookApp] Kernel shutdown: c39940f8-0f91-41ad-9392-fd3ce3d0905a
[I 10:43:42.278 NotebookApp] Kernel shutdown: 2defaa68-de94-45b0-a44c-82313bd1db93
[I 10:43:42.584 NotebookApp] Starting buffering for 2defaa68-de94-45b0-a44c-82313bd1db93:cf398b2466cb4d2a8a8b20179c5fd721
[I 10:43:42.597 NotebookApp] Kernel shutdown: 2defaa68-de94-45b0-a44c-82313bd1db93
[I 10:44:11.165 NotebookApp] Creating new notebook in /Validador
[I 10:44:12.962 NotebookApp] Kernel started: 13ea9a6a-5c92-4655-873f-cbf69d8ab488, name: python3
[I 10:44:23.373 NotebookApp] Creating new file in /Validador
[I 10:45:14.716 NotebookApp] Creating new notebook in /Validador
[I 10:45:16.792 NotebookApp] Kernel started: f77565ef-ebfc-414e-9a54-02b3da58b181, name: python3
[I 10:46:13.893 NotebookApp] Saving file at /Validador/Untitled.ipynb
[I 10:46:29.467 NotebookApp] Saving file at /Validador/Obter dados periodo.txt
[I 10:46:33.893 NotebookApp] Starting buffering for 13ea9a6a-5c92-4655-873f-cbf69d8ab488:d37335f7741447ee9b9ef01fc0f5145e
[I 10:46:41.266 NotebookApp] Starting buffering for 385df0ca-33ec-4f56-be41-e7a792240d61:a3ec8c1f782742828145584db4db2788
[I 10:46:51.632 NotebookApp] Kernel shutdown: 13ea9a6a-5c92-4655-873f-cbf69d8ab488
[W 10:46:51.654 NotebookApp] delete /Validador/Untitled.ipynb
[I 10:47:16.863 NotebookApp] Saving file at /Validador/Observação de Periodo 7.ipynb
[I 10:49:16.917 NotebookApp] Saving file at /Validador/Observação de Periodo 7.ipynb
[I 11:17:16.477 NotebookApp] Saving file at /Validador/Observação de Periodo 7.ipynb
[I 11:19:16.574 NotebookApp] Saving file at /Validador/Observação de Periodo 7.ipynb
[W 11:19:21.163 NotebookApp] Notebook ResultadoFuturo/Resultado Futuro - ABEV3.ipynb is not trusted
[W 11:19:38.747 NotebookApp] Notebook ResultadoFuturo/Resultado Futuro - ABEV3.ipynb is not trusted
[I 11:25:16.418 NotebookApp] Saving file at /Validador/Observação de Periodo 7.ipynb
[I 11:27:16.494 NotebookApp] Saving file at /Validador/Observação de Periodo 7.ipynb
[I 11:29:16.502 NotebookApp] Saving file at /Validador/Observação de Periodo 7.ipynb
[I 11:58:07.463 NotebookApp] Starting buffering for 19005701-50eb-4eb9-8a67-a0496a5ebcf6:25479e9bbc4c45beade12f0cbc9667ee
[I 11:58:08.110 NotebookApp] Starting buffering for f77565ef-ebfc-414e-9a54-02b3da58b181:61979cff5ba04c6b8eb5e90d36d02e22
